apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-sample
spec:
  # Add required fields here
  # TODO: Remove replicas since kubebuilder is defaulting to 2.
  replicas: 2
