apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: contour-sample
  namespace: projectcontour
spec:
  networkPublishing:
    envoy:
      type: ClusterIPService
